WEB_APP_NAME: "Your Website name"
CONTACT_US_PHONE: "+Your contact_phone" # Format => 1 (123) 123-1234 Will be displayed in Footer

# DB settings
DB_NAME: "Your DB name" #used for developpement
DB_USER_NAME: "Your DB User Name"
DB_PASSWORD: "Your DB user password"
DB_HOSTNAME: "Your DB HOSTNAME"
# TEST ENV
TEST_DB_NAME: "Your test DB_NAME"
TEST_DB_HOST: "Your test DB_HOSTNAME"
# Production env
PRODUCTION_DB_HOST: "Your production DB_HOSTNAME"
PRODUCTION_DB_NAME: "Your Production DB_NAME"

# TrueMail settings

TRUE_MAIL_VERIFIER: 'Your E-mail' # Can use your own personnal e-mail, but is recommended to use the same mailer as the one used for this website if setup.
VERIFIER_DOMAIN: "Your E-Mail verifier Domain" #Ex: gmail.com

# Mailer settings for PRODUCTION env
ACTION_MAILER_CACHING: false # Boolean value
MAILER_DELIVERY_METHOD: :smtp # Default value
MAILER_HOST: 'yoururl.com' #replace with your own url"
MAILER_DEFAULT_URL_OPTIONS_PROTOCOL: "https" # default value
MAILER_SENDER: 'change-me@example.com'
  # # SMTP settings
SMTP_ADDRESS: "smtp.yourMailerServiceDomain.com"
SMTP_PORT: 25 # default value
SMTP_USERNAME: 'your-username'
SMTP_PASSWORD: 'your-password'
SMTP_AUTHENTICATION: 'plain' # Default value
SMTP_ENABLE_STARTTLS_AUTO: true #boolean